package com.qaguild.dbeaver.processors.jdbi;

import com.qaguild.dbeaver.annotations.Column;
import com.qaguild.dbeaver.annotations.Id;
import com.qaguild.dbeaver.processors.AbstractProcessor;
import com.qaguild.dbeaver.processors.Utils;
import org.jdbi.v3.core.Jdbi;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class SaveEntityProcessor extends AbstractProcessor<Jdbi> {

    public SaveEntityProcessor(Jdbi executor) {
        super(executor);
    }

    @Override
    public String getName() {
        return "save";
    }

    @Override
    public Object process(Method method, Class<?> clazz, Object[] args) {
        String table = Utils.getTableName(clazz);
        Object object = args[0];

        ParameterData parameterData = getQueryParams(object);

        if (findById(object, table).isPresent()) {
            String query = prepareUpdate(object, table, parameterData);
            return executor.withHandle(h -> h.execute(query));
        }

        String query = prepareInsert(table, parameterData);
        return executor.withHandle(h -> h.execute(query));
    }

    private Optional<?> findById(Object object, String table) {
        Field id = getIdField(object);
        String idName = getFieldName(id);
        String idValue = getFieldValue(id, object);
        String query = String.format("SELECT * FROM %s WHERE %s = %s", table, idName, idValue);
        return executor.withHandle(h -> h.select(query).mapToBean(object.getClass()).findOne());
    }

    private String prepareInsert(String table, ParameterData parameterData) {
        String fields = String.join(",", parameterData.getFields());
        String values = String.join(",", parameterData.getValues());

        return String.format("INSERT INTO %s(%s) VALUES(%s)",
                table,
                fields,
                values);
    }

    private String prepareUpdate(Object object, String table, ParameterData parameterData) {
        List<String> fields = parameterData.getFields();
        List<String> values = parameterData.getValues();

        List<String> result = new ArrayList<>();

        for (int i = 0; i < fields.size(); i++) {
            String name = fields.get(i);
            String value = values.get(i);
            result.add(String.format("%s = %s", name, value));
        }
        String params = String.join(",", result);

        Field id = getIdField(object);
        String idName = getFieldName(id);
        String idValue = getFieldValue(id, object);

        return String.format("UPDATE %s SET %s WHERE %s = %s",
                table,
                params,
                idName,
                idValue);
    }

    private ParameterData getQueryParams(Object parameter) {
        List<String> values = new ArrayList<>();
        List<String> fields = new ArrayList<>();
        Field[] declaredFields = parameter.getClass().getDeclaredFields();

        for (Field field : declaredFields) {
            if (isAutogeneratedId(field)) {
                continue;
            }

            String fieldName = getFieldName(field);
            String fieldValue = getFieldValue(field, parameter);

            values.add(fieldValue);
            fields.add(fieldName);
        }
        return new ParameterData(fields, values);
    }

    private boolean isAutogeneratedId(Field field) {
        Id id = field.getDeclaredAnnotation(Id.class);
        return id != null && id.generated();
    }

    private String getFieldValue(Field field, Object parameter) {
        if (field == null) {
            return null;
        }
        field.setAccessible(true);

        try {
            String value = field.get(parameter).toString();
            if (field.getType() == String.class) {
                return String.format("'%s'", value);
            }
            return value;
        } catch (IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }

    private String getFieldName(Field field) {
        if (field == null) {
            return null;
        }

        String fieldName = field.getName();
        Column annotation = field.getDeclaredAnnotation(Column.class);
        if (annotation != null) {
            return annotation.value();
        }
        return fieldName;
    }

    private boolean isId(Field field) {
        Id id = field.getDeclaredAnnotation(Id.class);
        return id != null;
    }

    private Field getIdField(Object parameter) {
        Field[] declaredFields = parameter.getClass().getDeclaredFields();
        for (Field field : declaredFields) {
            if (isId(field)) {
                return field;
            }
        }
        return null;
    }
}

class ParameterData {

    private final List<String> fields;
    private final List<String> values;

    public ParameterData(List<String> fields, List<String> values) {
        this.fields = fields;
        this.values = values;
    }

    public List<String> getFields() {
        return fields;
    }

    public List<String> getValues() {
        return values;
    }
}